export const DEPOSIT_REQUEST = 'DEPOSIT_REQUEST';
export const DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS';
export const DEPOSIT_FAIL = 'DEPOSIT_FAIL';

export const ALL_DEPOSIT_REQUEST = 'ALL_DEPOSIT_REQUEST';

export const ALL_DEPOSIT_SUCCESS = 'ALL_DEPOSIT_SUCCESS';
export const ALL_DEPOSIT_FAIL = 'ALL_DEPOSIT_FAIL';

export const DEPOSIT_RESET = 'DEPOSIT_RESET';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
