export const PAYMENT_METHOD_REQUEST = 'PAYMENT_METHOD_REQUEST';
export const PAYMENT_METHOD_SUCCESS = 'PAYMENT_METHOD_SUCCESS';
export const PAYMENT_METHOD_FAILURE = 'PAYMENT_METHOD_FAILURE';

export const PAYMENT_METHOD_REQUEST_ALL = 'PAYMENT_METHOD_REQUEST_ALL';
export const PAYMENT_METHOD_SUCCESS_ALL = 'PAYMENT_METHOD_SUCCESS_ALL';
export const PAYMENT_METHOD_FAILURE_ALL = 'PAYMENT_METHOD_FAILURE_ALL';

export const CLEAT_ERRORS = 'CLEAT_PAYMENT_METHOD';
