export const WITHDRAW_CREATE_REQUEST = 'WITHDRAW_REQUEST';
export const WITHDRAW_CREATE_SUCCESS = 'WITHDRAW_SUCCESS';
export const WITHDRAW_CREATE_FAILURE = 'WITHDRAW_FAILURE';

export const WITHDRAW_LIST_REQUEST = 'WITHDRAW_LIST_REQUEST';
export const WITHDRAW_LIST_SUCCESS = 'WITHDRAW_LIST_SUCCESS';
export const WITHDRAW_LIST_FAILURE = 'WITHDRAW_LIST_FAILURE';

export const ACTIVE_B_W_REQUEST = 'ACTIVE_BALANCE_WITHDRAW_REQUEST';
export const ACTIVE_B_W_SUCCESS = 'ACTIVE_BALANCE_WITHDRAW_SUCCESS';
export const ACTIVE_B_W_FAILURE = 'ACTIVE_BALANCE_WITHDRAW_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
